version: "3.8"

services:
  db_mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./.docker-data/mongo/data/db:/data/db
      - ./.docker-data/mongo/data/configdb:/data/configdb
