// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_rpc_op_ from "./routes/api/rpc/[op].ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $local_work from "./routes/local-work.tsx";
import * as $project_projectId_ from "./routes/project/[projectId].tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DevelopmentPage from "./islands/DevelopmentPage.tsx";
import * as $LocalProjectDevelopmentPage from "./islands/LocalProjectDevelopmentPage.tsx";
import * as $MainLayout from "./islands/MainLayout.tsx";
import * as $ProjectDetailPage from "./islands/ProjectDetailPage.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/rpc/[op].ts": $api_rpc_op_,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/local-work.tsx": $local_work,
    "./routes/project/[projectId].tsx": $project_projectId_,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/DevelopmentPage.tsx": $DevelopmentPage,
    "./islands/LocalProjectDevelopmentPage.tsx": $LocalProjectDevelopmentPage,
    "./islands/MainLayout.tsx": $MainLayout,
    "./islands/ProjectDetailPage.tsx": $ProjectDetailPage,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
