FROM node:18-alpine

WORKDIR /app

# COPY ./package*.json ./
COPY ./ .
RUN npm ci

ENV NODE_ENV=production
ENV ENV_TYPE=production
ENV PORT=3000

RUN npm run build -w @mx/web-firmix-nextjs

EXPOSE 3000

CMD ["npm", "run", "start", "-w", "@mx/web-firmix-nextjs"]
