FROM node:18-alpine

WORKDIR /app

# COPY ./package*.json ./
COPY ./ .
RUN npm ci

RUN npm run build -w @mx/web-kfx

ENV NODE_ENV=production
ENV ENV_TYPE=production
ENV PORT=3000
EXPOSE 3000

CMD ["npm", "run", "start", "-w", "@mx/web-kfx"]
