import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { fallbackValues } from "../base/fallback_values";
import { clientStorageImpl } from "../central/system/client_storage_impl";
import { SiteContextValue } from "../common/site_context";
import { MainLayout } from "../screens/MainLayout";
import { SiteContextProvider } from "../screens/SiteContextProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const loginUser = clientStorageImpl.readCookieLoginUserClue() ?? null;
  const coactiveState =
    clientStorageImpl.readCookieCoactiveState() ?? fallbackValues.coactiveState;
  const siteContextValue: SiteContextValue = {
    pagePath: "__dummy",
    loginUser,
    coactiveState,
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <SiteContextProvider value={siteContextValue}>
          <MainLayout>{children}</MainLayout>
        </SiteContextProvider>
      </body>
    </html>
  );
}
